stages:
  - build

stage_build:
  stage: build
  image: python:3
  tags:
    - gitlab-server
  script:
    - cp $ENV_FILE .env
    - pip install flask psycopg2 pytest python-dotenv
    - python test_app.py