version: '3'
services:
  flask:
    image: shalunbdk/shalin-portal:latest # Использование образа из Docker Hub
    container_name: shalin-portal-flask
    env_file:
      - .env
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - db
    command: sh -c "cd shalin-portal && python ADConnect.py && python app.py"
  

  db:
    image: postgres:14  # Образ PostgreSQL
    container_name: shalin-portal-db
    environment:
      - POSTGRES_DB: db
      - POSTGRES_USER: shalin-ar
      - POSTGRES_PASSWORD: 123QshI098
    volumes:
      - pgdata:/var/lib/postgresql/data  # Хранение данных вне контейнера
    restart: always

volumes:
  pgdata: