version: '3'
services:
  flask:
    image: shalunbdk/shalin-portal:latest # Использование образа из Docker Hub
    container_name: shalin-portal-flask
    environment:
      - PYTHONUNBUFFERED=True
      - POSTGRES_DB=${POSTGRES_DB}  # Имя базы данных
      - POSTGRES_USER=${POSTGRES_USER}  # Пользователь БД
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Пароль пользователя
      - POSTGRES_HOST=db  # Имя сервиса PostgreSQL
      - AD_SERVER=${AD_SERVER}
      - AD_USER=${AD_USER}
      - AD_PASSWORD=${AD_PASSWORD}
      - AD_BASE_DN=${AD_BASE_DN}
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - db
    command: sh -c "python /shalin-portal/ADConnect.py && python app.py"
  
  db:
    image: postgres:14  # Образ PostgreSQL
    container_name: shalin-portal-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data  # Хранение данных вне контейнера
    restart: always

volumes:
  pgdata: